/+
var a2, b, i2, n2, f2;
var a = null;
var i = null;
var n = null;
var f = null;
if ((a2 = a) !== null) {
}
if ((b = a) instanceof B) {
}
if ((i2 = i) !== null) {
}
if ((n2 = n) !== null) {
}
if ((f2 = f) !== null) {
}
+/

extern class A {}
extern class B is A {}
A? a = null
int? i = null
int[]? n = null
void fn()? f = null
if A a = a {}
if B b = a {}
if int i = i {}
if int[] n = n {}
if void fn() f = f {}
